# Production environment values
replicaCount: 3

# Use production tag
image:
  tag: latest

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: site-monitor.example.com
      paths: ["/"]
  tls:
    - secretName: site-monitor-prod-tls
      hosts:
        - site-monitor.example.com

# Higher resource limits for production
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Application configuration for production
appConfig:
  env: production
  logLevel: INFO
  defaultCheckInterval: 60
  minCheckInterval: 30
  responseTimeThreshold: 1000
  enableRateLimiting: true

# Use larger persistent storage in production
prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 10Gi

grafana:
  persistence:
    enabled: true
    size: 5Gi
