name: Site Monitor Pro CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install security scanning tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Scan Python dependencies for vulnerabilities
        run: |
          cd backend
          safety check -r requirements.txt || true

      - name: Run SAST with Bandit
        run: |
          cd backend
          bandit -r app/ -f json -o bandit-results.json || true

      - name: Upload Bandit scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-results
          path: backend/bandit-results.json
          retention-days: 30

  deploy-to-render:
    needs: [test-backend, security-scan]
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
